environment:
  global:
    MINGW_64: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64
    PYTHON: C:\Python34-x64
    PYTHON_VERSION: 3.4

#matrix:
#  - PYTHON: C:\Python36-x64
#    PYTHON_VERSION: 3.6
#    PYTHON_ARCH: 64

install:
  #- appveyor DownloadFile https://github.com/rogerbinns/apsw/releases/download/3.28.0-r1/apsw-3.28.0-r1.win-amd64-py3.6.exe
  #- start "" /wait "apsw-3.28.0-r1.win-amd64-py3.6.exe" /S
  - appveyor DownloadFile https://github.com/lmdu/mingw64/raw/master/i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z -FileName mw32.7z
  - 7z x -oC:\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0 mw32.7z > NUL
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - SET PATH=%MINGW_64%\bin;%PATH%
  - SET PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
  - gendef %PYTHON%\vcruntime140.dll
  - dlltool -D %PYTHON%\vcruntime140.dll -d vcruntime140.def -l %PYTHON%\libs\libvcruntime140.a
  - python -m pip install apsw-wheels
  - python -m pip install pywin32
  #- appveyor DownloadFile https://download.lfd.uci.edu/pythonlibs/n5jyqt7p/PySide-1.2.4-cp36-cp36m-win_amd64.whl
  #- python -m pip install PySide-1.2.4-cp36-cp36m-win_amd64.whl
  - python -m pip install -r requirements.txt
  - python ci\fix_compiler_error.py %PYTHON%
  #- copy /y %PYTHON%\lib\site-packages\shiboken2\shiboken2.abi3.dll %PYTHON%\lib\site-packages\PySide2
  - appveyor DownloadFile https://github.com/upx/upx/releases/download/v3.95/upx-3.95-win64.zip
  - 7z e upx-3.95-win64.zip *.exe -r

build_script:
  - cd src\libs\src
  - python setup.py build_ext --inplace -c mingw32
  - move /y *.pyd ..
  - cd ..\..\..
  - pyinstaller win.spec
  #- copy /y %PYTHON%\lib\site-packages\PySide2\QtWebEngineProcess.exe dist\Krait\PySide2
  #- copy /y %PYTHON%\lib\site-packages\PySide2\resources\* dist\Krait\PySide2
  - cd setup
  - iscc win.iss
  - cd ..

artifacts:
  - path: "setup\\*.exe"
    name: Krait

deploy:
  description: 'krait installer'
  provider: GitHub
  auth_token:
    secure: nEMr2O2SlD36EH1mxXWWtOqrp3djzlK1kQY8SkFDyWwxA2UzN5XryHy8BmdNo7CT
  on:
    appveyor_repo_tag: true